#! /bin/sh

$HOME/.config/polybar/launcher.sh

pgrep -x sxhkd > /dev/null || sxhkd &
#pgrep -x picom > /dev/null || picom --experimental-backends &
pgrep -x picom > /dev/null || picom --config $HOME/.config/picom/picom.conf &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

#border of the window
bspc config border_width        1 
#Space of the windows
#bspc config window_gap          5 
bspc config window_gap          3

#bspc config split_ratio          0.52
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a Zathura state=tiled

#Wallpaper
#feh --bg-fill /home/paul/Images/barca3.png &
#feh --bg-fill /home/paul/Images/walp_arch5.jpg &
feh --bg-fill /home/paul/Images/wallpapers/wallp_server.jpg &

#Configuracion de teclado
setxkbmap latam &
#setxkbmap -layout latam

#Configuracion de luz nocturna
redshift -O 3700K -r -P
